<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS2rNNWh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS2rNNWh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS2rNNWh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS2rNNWh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS2rNNWh\App_KernelDevDebugContainer([
    'container.build_hash' => 'S2rNNWh',
    'container.build_id' => '78336b84',
    'container.build_time' => 1763457661,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS2rNNWh');
